// Generated by gencpp from file camera_processor/PointDepth.msg
// DO NOT EDIT!


#ifndef CAMERA_PROCESSOR_MESSAGE_POINTDEPTH_H
#define CAMERA_PROCESSOR_MESSAGE_POINTDEPTH_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace camera_processor
{
template <class ContainerAllocator>
struct PointDepth_
{
  typedef PointDepth_<ContainerAllocator> Type;

  PointDepth_()
    : header()
    , depths()  {
    }
  PointDepth_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , depths(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _depths_type;
  _depths_type depths;





  typedef boost::shared_ptr< ::camera_processor::PointDepth_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::camera_processor::PointDepth_<ContainerAllocator> const> ConstPtr;

}; // struct PointDepth_

typedef ::camera_processor::PointDepth_<std::allocator<void> > PointDepth;

typedef boost::shared_ptr< ::camera_processor::PointDepth > PointDepthPtr;
typedef boost::shared_ptr< ::camera_processor::PointDepth const> PointDepthConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::camera_processor::PointDepth_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::camera_processor::PointDepth_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::camera_processor::PointDepth_<ContainerAllocator1> & lhs, const ::camera_processor::PointDepth_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.depths == rhs.depths;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::camera_processor::PointDepth_<ContainerAllocator1> & lhs, const ::camera_processor::PointDepth_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace camera_processor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::camera_processor::PointDepth_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_processor::PointDepth_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::camera_processor::PointDepth_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::camera_processor::PointDepth_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_processor::PointDepth_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_processor::PointDepth_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::camera_processor::PointDepth_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9458e1769307167ea54afd5c9deb9fc4";
  }

  static const char* value(const ::camera_processor::PointDepth_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9458e1769307167eULL;
  static const uint64_t static_value2 = 0xa54afd5c9deb9fc4ULL;
};

template<class ContainerAllocator>
struct DataType< ::camera_processor::PointDepth_<ContainerAllocator> >
{
  static const char* value()
  {
    return "camera_processor/PointDepth";
  }

  static const char* value(const ::camera_processor::PointDepth_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::camera_processor::PointDepth_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32[] depths\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::camera_processor::PointDepth_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::camera_processor::PointDepth_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.depths);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PointDepth_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::camera_processor::PointDepth_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::camera_processor::PointDepth_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "depths[]" << std::endl;
    for (size_t i = 0; i < v.depths.size(); ++i)
    {
      s << indent << "  depths[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.depths[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMERA_PROCESSOR_MESSAGE_POINTDEPTH_H
